# 시작
name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest  # 이 작업은 'ubuntu-latest' 환경에서 실행됩니다.

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # 레포지토리의 최신 코드를 체크아웃

    - name: execute remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd /home/ubuntu/image-okane-on-cliff
          git pull
          ./deploy.sh